### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by siddarth09** [chvmp/champ_setup_assistant#14]
Traceback (most recent call last):
  File "/home/siddarth/spot_ws/src/champ_setup_assistant/scripts/setup_assistant.py", line 28, in <module>
    from python_qt_binding.QtGui import *
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/__init__.py", line 55, in <module>
    from .binding_helper import loadUi, QT_BINDING, QT_BINDING_MODULES, QT_BINDING_VERSION  # @UnusedImport
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 276, in <module>
    getattr(sys, 'SELECT_QT_BINDING_ORDER', None),
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 120, in _select_qt_binding
    (', '.join(["'%s'" % b for b in binding_order]), '\n'.join(error_msgs)))
ImportError: Could not find Qt binding (looked for: 'pyqt', 'pyside'):
  ImportError for 'pyqt': No module named PyQt5.QtCore
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 108, in _select_qt_binding
    QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 153, in _load_pyqt
    _named_import('PyQt5.%s' % module_name)
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 133, in _named_import
    module = builtins.__import__(name)
ImportError: No module named PyQt5.QtCore

  ImportError for 'pyside': No module named PySide2.QtCore
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 108, in _select_qt_binding
    QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 185, in _load_pyside
    _named_import('PySide2.%s' % module_name)
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 133, in _named_import
    module = builtins.__import__(name)
ImportError: No module named PySide2.QtCore

[champ_setup_assistant-2] process has died [pid 5162, exit code 1, cmd /home/siddarth/spot_ws/src/champ_setup_assistant/scripts/setup_assistant.py __name:=champ_setup_assistant __log:=/home/siddarth/.ros/log/1c413f5c-8813-11ec-9d50-9bc8d25ccedf/champ_setup_assistant-2.log].
log file: /home/siddarth/.ros/log/1c413f5c-8813-11ec-9d50-9bc8d25ccedf/champ_setup_assistant-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by siddarth09** [comment]
I installed pyside and pyqt5, am using ubuntu 20 with noetic distro.  please  help me out

**Comment by rpangrazio** [comment]
I got it working by changing the first line of setup_assistant.py to
#!/usr/bin/env python3
