### ISSUE TITLE
Robot is not visible in setup assistant.

### ISSUE THREAD

**Issue by alphabeta97** [chvmp/champ_setup_assistant#5]
I'm running it on ros melodic. After loading URDF file the robot is not visible. I've tried it with URDF I've made and also with open-quadruped and ANYmal.
Also there is an error of robot state publisher when I launch setup_assistant.

**Comment by abdu7rahman** [comment]
i am running it on ros noetic, and i am unable to load the urdf at all
  process[champ_setup_assistant-1]: started with pid [19278]
  Unknown tag "self_filter" in /robot[@name='anymal']/link[@name='base']
  Traceback (most recent call last):
    File "/home/abdulrahman/kalb_ws/src/champ_setup_assistant/scripts/rviz_widget.py", line 121, in on_urdf_path_load
      self.main.robot.load_urdf(urdf_path)
    File "/home/abdulrahman/kalb_ws/src/champ_setup_assistant/scripts/urdf_parser.py", line 55, in load_urdf
      self.end_links = self.get_end_links()
    File "/home/abdulrahman/kalb_ws/src/champ_setup_assistant/scripts/urdf_parser.py", line 205, in get_end_links
      if not self.link_has_child(link) and not self.link_attached_to_base(link):
    File "/home/abdulrahman/kalb_ws/src/champ_setup_assistant/scripts/urdf_parser.py", line 174, in link_has_child
      return self.robot.child_map.has_key(link_name)
  AttributeError: 'dict' object has no attribute 'has_key'
